if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/BboTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/BboTest-b12d07c_tests.cmake")
else()
  add_test(BboTest_NOT_BUILT-b12d07c BboTest_NOT_BUILT-b12d07c)
endif()
