if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/BookStoreTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/BookStoreTest-b12d07c_tests.cmake")
else()
  add_test(BookStoreTest_NOT_BUILT-b12d07c BookStoreTest_NOT_BUILT-b12d07c)
endif()
