# CMake generated Testfile for 
# Source directory: /Users/hamzalatif/Desktop/low-latency-trading/tests
# Build directory: /Users/hamzalatif/Desktop/low-latency-trading/build-release/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/logger_tests-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/strong_type_tests-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/price_type_tests-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/level_tests-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/quote_tests-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/trade_tests-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/market_event_tests-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/spsc_ringbuffer_tests-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/SpscRingBufferConcurrencyTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/AtomicTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/MarketEventTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/FeedHandlerMockTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/UdpMarketDataSourceTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/UdpFeedHandlerTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/UdpCodecTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/FeedHandlerUdpIntegrationTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/SimpleStrategyTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/StrategyEngineTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/ItchDecoderTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/ItchDispatcherTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/ItchStreamReaderTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/ItchReplayTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/AddOrderWithMpidMessageTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/TradeMessageTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/CrossTradeMessageTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/BrokenTradeMessageTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/StockTradingActionMessageTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/MarketParticipantPositionMessageTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/RemainingItchMessagesTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/InstrumentStoreTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/ItchNormalizerTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/OrderStoreTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/PriceLevelTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/BookSideTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/OrderBookTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/BookStoreTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/OrderBookAddIntegrationTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/OrderBookLifecycleIntegrationTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/OrderBookIntegrityTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/BboTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/BboChangeIntegrationTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/ItchQuotePublisherTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/ItchQuotePipelineIntegrationTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/MarketEventConsumerTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/ItchUdpCodecTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/UdpItchMarketDataSourceTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/ItchSequenceRecoveryTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/ItchFeedHandlerTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/ItchUdpFeedIntegrationTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/ItchUdpQuotePipelineIntegrationTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/ItchTradePublicationTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/FileItchRecoverySourceTest-b12d07c_include.cmake")
