if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/ItchSequenceRecoveryTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/ItchSequenceRecoveryTest-b12d07c_tests.cmake")
else()
  add_test(ItchSequenceRecoveryTest_NOT_BUILT-b12d07c ItchSequenceRecoveryTest_NOT_BUILT-b12d07c)
endif()
