if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/ItchQuotePublisherTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/ItchQuotePublisherTest-b12d07c_tests.cmake")
else()
  add_test(ItchQuotePublisherTest_NOT_BUILT-b12d07c ItchQuotePublisherTest_NOT_BUILT-b12d07c)
endif()
