if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/ItchDecoderTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/ItchDecoderTest-b12d07c_tests.cmake")
else()
  add_test(ItchDecoderTest_NOT_BUILT-b12d07c ItchDecoderTest_NOT_BUILT-b12d07c)
endif()
