if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/ItchFeedHandlerTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/ItchFeedHandlerTest-b12d07c_tests.cmake")
else()
  add_test(ItchFeedHandlerTest_NOT_BUILT-b12d07c ItchFeedHandlerTest_NOT_BUILT-b12d07c)
endif()
