if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/OrderBookTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/OrderBookTest-b12d07c_tests.cmake")
else()
  add_test(OrderBookTest_NOT_BUILT-b12d07c OrderBookTest_NOT_BUILT-b12d07c)
endif()
