if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/OrderBookAddIntegrationTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/OrderBookAddIntegrationTest-b12d07c_tests.cmake")
else()
  add_test(OrderBookAddIntegrationTest_NOT_BUILT-b12d07c OrderBookAddIntegrationTest_NOT_BUILT-b12d07c)
endif()
