if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/OrderBookIntegrityTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/OrderBookIntegrityTest-b12d07c_tests.cmake")
else()
  add_test(OrderBookIntegrityTest_NOT_BUILT-b12d07c OrderBookIntegrityTest_NOT_BUILT-b12d07c)
endif()
