if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/StockTradingActionMessageTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/StockTradingActionMessageTest-b12d07c_tests.cmake")
else()
  add_test(StockTradingActionMessageTest_NOT_BUILT-b12d07c StockTradingActionMessageTest_NOT_BUILT-b12d07c)
endif()
