if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/StrategyEngineTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/StrategyEngineTest-b12d07c_tests.cmake")
else()
  add_test(StrategyEngineTest_NOT_BUILT-b12d07c StrategyEngineTest_NOT_BUILT-b12d07c)
endif()
