if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/strong_type_tests-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/strong_type_tests-b12d07c_tests.cmake")
else()
  add_test(strong_type_tests_NOT_BUILT-b12d07c strong_type_tests_NOT_BUILT-b12d07c)
endif()
