if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/TradeMessageTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-release/tests/TradeMessageTest-b12d07c_tests.cmake")
else()
  add_test(TradeMessageTest_NOT_BUILT-b12d07c TradeMessageTest_NOT_BUILT-b12d07c)
endif()
