if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/AddOrderWithMpidMessageTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/AddOrderWithMpidMessageTest-b12d07c_tests.cmake")
else()
  add_test(AddOrderWithMpidMessageTest_NOT_BUILT-b12d07c AddOrderWithMpidMessageTest_NOT_BUILT-b12d07c)
endif()
