if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/BboChangeIntegrationTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/BboChangeIntegrationTest-b12d07c_tests.cmake")
else()
  add_test(BboChangeIntegrationTest_NOT_BUILT-b12d07c BboChangeIntegrationTest_NOT_BUILT-b12d07c)
endif()
