if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/BookSideTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/BookSideTest-b12d07c_tests.cmake")
else()
  add_test(BookSideTest_NOT_BUILT-b12d07c BookSideTest_NOT_BUILT-b12d07c)
endif()
