if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/BrokenTradeMessageTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/BrokenTradeMessageTest-b12d07c_tests.cmake")
else()
  add_test(BrokenTradeMessageTest_NOT_BUILT-b12d07c BrokenTradeMessageTest_NOT_BUILT-b12d07c)
endif()
