# CMake generated Testfile for 
# Source directory: /Users/hamzalatif/Desktop/low-latency-trading/tests
# Build directory: /Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/logger_tests-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/strong_type_tests-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/price_type_tests-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/level_tests-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/quote_tests-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/trade_tests-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/market_event_tests-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/spsc_ringbuffer_tests-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/SpscRingBufferConcurrencyTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/AtomicTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/MarketEventTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/FeedHandlerMockTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/UdpMarketDataSourceTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/UdpFeedHandlerTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/UdpCodecTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/FeedHandlerUdpIntegrationTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/SimpleStrategyTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/StrategyEngineTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/ItchDecoderTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/ItchDispatcherTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/ItchStreamReaderTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/ItchReplayTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/AddOrderWithMpidMessageTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/TradeMessageTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/CrossTradeMessageTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/BrokenTradeMessageTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/StockTradingActionMessageTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/MarketParticipantPositionMessageTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/RemainingItchMessagesTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/InstrumentStoreTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/ItchNormalizerTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/OrderStoreTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/PriceLevelTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/BookSideTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/OrderBookTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/BookStoreTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/OrderBookAddIntegrationTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/OrderBookLifecycleIntegrationTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/OrderBookIntegrityTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/BboTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/BboChangeIntegrationTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/ItchQuotePublisherTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/ItchQuotePipelineIntegrationTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/MarketEventConsumerTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/ItchUdpCodecTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/UdpItchMarketDataSourceTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/ItchSequenceRecoveryTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/ItchFeedHandlerTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/ItchUdpFeedIntegrationTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/ItchUdpQuotePipelineIntegrationTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/ItchTradePublicationTest-b12d07c_include.cmake")
include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/FileItchRecoverySourceTest-b12d07c_include.cmake")
