if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/FeedHandlerMockTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/FeedHandlerMockTest-b12d07c_tests.cmake")
else()
  add_test(FeedHandlerMockTest_NOT_BUILT-b12d07c FeedHandlerMockTest_NOT_BUILT-b12d07c)
endif()
