if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/ItchUdpFeedIntegrationTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/ItchUdpFeedIntegrationTest-b12d07c_tests.cmake")
else()
  add_test(ItchUdpFeedIntegrationTest_NOT_BUILT-b12d07c ItchUdpFeedIntegrationTest_NOT_BUILT-b12d07c)
endif()
