if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/ItchNormalizerTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/ItchNormalizerTest-b12d07c_tests.cmake")
else()
  add_test(ItchNormalizerTest_NOT_BUILT-b12d07c ItchNormalizerTest_NOT_BUILT-b12d07c)
endif()
