if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/logger_tests-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/logger_tests-b12d07c_tests.cmake")
else()
  add_test(logger_tests_NOT_BUILT-b12d07c logger_tests_NOT_BUILT-b12d07c)
endif()
