if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/MarketParticipantPositionMessageTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/MarketParticipantPositionMessageTest-b12d07c_tests.cmake")
else()
  add_test(MarketParticipantPositionMessageTest_NOT_BUILT-b12d07c MarketParticipantPositionMessageTest_NOT_BUILT-b12d07c)
endif()
