if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/MarketEventTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/MarketEventTest-b12d07c_tests.cmake")
else()
  add_test(MarketEventTest_NOT_BUILT-b12d07c MarketEventTest_NOT_BUILT-b12d07c)
endif()
