if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/OrderStoreTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/OrderStoreTest-b12d07c_tests.cmake")
else()
  add_test(OrderStoreTest_NOT_BUILT-b12d07c OrderStoreTest_NOT_BUILT-b12d07c)
endif()
