if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/SimpleStrategyTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/SimpleStrategyTest-b12d07c_tests.cmake")
else()
  add_test(SimpleStrategyTest_NOT_BUILT-b12d07c SimpleStrategyTest_NOT_BUILT-b12d07c)
endif()
