if(EXISTS "/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/UdpMarketDataSourceTest-b12d07c_tests.cmake")
  include("/Users/hamzalatif/Desktop/low-latency-trading/build-profile/tests/UdpMarketDataSourceTest-b12d07c_tests.cmake")
else()
  add_test(UdpMarketDataSourceTest_NOT_BUILT-b12d07c UdpMarketDataSourceTest_NOT_BUILT-b12d07c)
endif()
